DNSmasq documentation update to use alongside AdGuard addon
home-assistant/hassio-addons pull request #1664
Opened 2020-11-01 14:14 UTC by Jupred

2020-11-01 19:34 UTC, pvizeli requested changes
First part is fine. Please remove the second part.

2020-11-01 19:34 UTC, pvizeli commented on dnsmasq/DOCS.md
> +```
Remove this part. We do not refer to other add-ons inside docs.

2020-11-01 19:37 UTC, Jupred commented
done

2020-11-02 11:28 UTC, pvizeli approved these changes

2020-11-02 11:28 UTC, merged